# Changes here will be overwritten by Copier
_commit: 1.29.5
_src_path: gh:DiamondLightSource/python-copier-template
author_email: joseph.ware@diamond.ac.uk
author_name: Joseph Ware
component_owner: group:default/sscc
description: TaskGraph plans for Bluesky
distribution_name: bluesky-taskgraph
docker: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: bluesky_taskgraph
pypi: true
repo_name: bluesky-taskgraph
type_checker: pyright
